# render.yaml
services:
  - type: web
    name: mood-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    workingDir: backend
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /var/cache/huggingface
